# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSMKampus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.0.0.beta.1'
  # Pods for FSMKampus

  target 'FSMKampusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FSMKampusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
